name: Build FinTrack

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-deb:
    name: Build Debian package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "25"
          cache: maven

      - name: Install packaging dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y fakeroot

      - name: Build application
        run: mvn clean package

      - name: Build DEB
        run: |
          jpackage \
            --type deb \
            --name fintrack \
            --app-version 2.0.0 \
            --input target/app \
            --main-jar fintrack-2.0.0-SNAPSHOT.jar \
            --main-class app.Main \
            --module-path target/app/lib \
            --add-modules javafx.controls,javafx.fxml,java.sql \
            --resource-dir resources-linux \
            --dest target/package \
            --icon src/main/java/app/assets/fintrack_ico.ico \
            --linux-shortcut

      - name: Upload DEB
        uses: actions/upload-artifact@v4
        with:
          name: fintrack-deb
          path: target/package/*.deb

  build-windows:
    name: Build Windows installer
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '25'
          cache: maven

      - name: Build application
        run: mvn clean package

      - name: Build EXE
        run: |
          jpackage `
            --type exe `
            --name FinTrack `
            --app-version 2.0.0 `
            --input target/app `
            --main-jar fintrack-2.0.0-SNAPSHOT.jar `
            --main-class app.Main `
            --module-path target/app/lib `
            --add-modules javafx.controls,javafx.fxml,java.sql `
            --dest target/package `
            --win-menu `
            --win-shortcut `
            --icon src/main/java/app/assets/fintrack.ico 

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: fintrack-windows
          path: target/package/*.exe